export const products = [
  { id: "product1", name: "Shoes", desc: "Comfortable running shoes.", price: 200, category: "Apparel" },
  { id: "product2", name: "Hat", desc: "Stylish summer hat.", price: 190, category: "Apparel" },
  { id: "product3", name: "Watch", desc: "Water-resistant wristwatch.", price: 1000, category: "Accessories" },
  { id: "product4", name: "Backpack", desc: "Durable travel backpack.", price: 699, category: "Travel" },
  { id: "product5", name: "Sunglasses", desc: "UV-protected sunglasses.", price: 399, category: "Accessories" },
  { id: "product6", name: "T-Shirt", desc: "100% cotton t-shirt.", price: 259, category: "Apparel" },
  { id: "product7", name: "Laptop", desc: "High-performance laptop.", price: 89999, category: "Electronics" },
  { id: "product8", name: "Smartphone", desc: "Latest model smartphone.", price: 6999, category: "Electronics" },
  { id: "product9", name: "Camera", desc: "DSLR camera with lens.", price: 49999, category: "Electronics" },
  { id: "product10", name: "Headphones", desc: "Noise-cancelling headphones.", price: 1499, category: "Electronics" },
  { id: "product11", name: "Tablet", desc: "10-inch HD display tablet.", price: 2999, category: "Electronics" },
  { id: "product12", name: "Bluetooth Speaker", desc: "Portable wireless speaker.", price: 799, category: "Electronics" },
  { id: "product13", name: "Fitness Tracker", desc: "Track your daily activity.", price: 1299, category: "Fitness" },
  { id: "product14", name: "Gaming Mouse", desc: "High-precision gaming mouse.", price: 599, category: "Electronics" },
  { id: "product15", name: "Mechanical Keyboard", desc: "RGB backlit keyboard.", price: 2499, category: "Electronics" },
  { id: "product16", name: "Desk Lamp", desc: "LED adjustable desk lamp.", price: 349, category: "Office Supplies" },
  { id: "product17", name: "Water Bottle", desc: "Insulated stainless steel bottle.", price: 299, category: "Fitness" },
  { id: "product18", name: "Notebook", desc: "Hardcover ruled notebook.", price: 199, category: "Office Supplies" },
  { id: "product19", name: "Pen Set", desc: "Premium gel pens (pack of 5).", price: 149, category: "Office Supplies" },
  { id: "product20", name: "Office Chair", desc: "Ergonomic mesh chair.", price: 5999, category: "Office Supplies" },
  { id: "product21", name: "Desk Organizer", desc: "Multi-compartment desk organizer.", price: 399, category: "Office Supplies" },
  { id: "product22", name: "Coffee Mug", desc: "Ceramic coffee mug.", price: 249, category: "Home & Kitchen" },
  { id: "product23", name: "Wireless Charger", desc: "Fast charging pad.", price: 899, category: "Electronics" },
  { id: "product24", name: "Power Bank", desc: "10000mAh portable charger.", price: 1199, category: "Electronics" },
  { id: "product25", name: "Tripod", desc: "Adjustable camera tripod.", price: 799, category: "Electronics" },
  { id: "product26", name: "Action Camera", desc: "Waterproof action camera.", price: 3999, category: "Electronics" },
  { id: "product27", name: "Smartwatch", desc: "Fitness and notifications on your wrist.", price: 4999, category: "Electronics" },
  { id: "product28", name: "Wireless Earbuds", desc: "True wireless stereo earbuds.", price: 1599, category: "Electronics" },
  { id: "product29", name: "Electric Kettle", desc: "1.5L automatic kettle.", price: 999, category: "Home & Kitchen" },
  { id: "product30", name: "Blender", desc: "Multi-speed kitchen blender.", price: 1799, category: "Home & Kitchen" },
  { id: "product31", name: "Toaster", desc: "2-slice pop-up toaster.", price: 799, category: "Home & Kitchen" },
  { id: "product32", name: "Microwave Oven", desc: "20L digital microwave.", price: 5999, category: "Home & Kitchen" },
  { id: "product33", name: "Air Fryer", desc: "Oil-less air fryer.", price: 3499, category: "Home & Kitchen" },
  { id: "product34", name: "Rice Cooker", desc: "Automatic rice cooker.", price: 1499, category: "Home & Kitchen" },
  { id: "product35", name: "Vacuum Cleaner", desc: "Bagless vacuum cleaner.", price: 3999, category: "Home & Kitchen" },
  { id: "product36", name: "Iron", desc: "Steam iron with non-stick soleplate.", price: 699, category: "Home & Kitchen" },
  { id: "product37", name: "Hair Dryer", desc: "Ionic hair dryer.", price: 899, category: "Home & Kitchen" },
  { id: "product38", name: "Shaver", desc: "Rechargeable electric shaver.", price: 1299, category: "Home & Kitchen" },
  { id: "product39", name: "Electric Toothbrush", desc: "Sonic electric toothbrush.", price: 999, category: "Home & Kitchen" },
  { id: "product40", name: "Face Mask", desc: "Pack of 50 disposable masks.", price: 299, category: "Fitness" },
  { id: "product41", name: "Hand Sanitizer", desc: "500ml alcohol-based sanitizer.", price: 199, category: "Fitness" },
  { id: "product42", name: "Yoga Mat", desc: "Non-slip yoga mat.", price: 499, category: "Fitness" },
  { id: "product43", name: "Dumbbell Set", desc: "Adjustable dumbbells (pair).", price: 2499, category: "Fitness" },
  { id: "product44", name: "Skipping Rope", desc: "Adjustable skipping rope.", price: 149, category: "Fitness" },
  { id: "product45", name: "Camping Tent", desc: "2-person waterproof tent.", price: 2999, category: "Travel" },
  { id: "product46", name: "Sleeping Bag", desc: "All-season sleeping bag.", price: 1199, category: "Travel" },
  { id: "product47", name: "Hiking Boots", desc: "Waterproof hiking boots.", price: 3499, category: "Travel" },
  { id: "product48", name: "Travel Pillow", desc: "Memory foam travel pillow.", price: 399, category: "Travel" },
  { id: "product49", name: "Suitcase", desc: "Hard shell cabin suitcase.", price: 3999, category: "Travel" },
  { id: "product50", name: "Wallet", desc: "Genuine leather wallet.", price: 799, category: "Accessories" },
]; 